apiVersion: v1
kind: ConfigMap
metadata:
  name: server-environment
data:
  DB_TYPE: mysqldb
  DB_MYSQLDB_DATABASE: "n8nio"
  DB_MYSQLDB_HOST: "mysql"
  DB_MYSQLDB_PORT: "3306"
  DB_MYSQLDB_USER: "n8n"
  GENERIC_TIMEZONE: "Europe/Berlin"
  TZ: "Europe/Berlin"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: n8n
