---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-server-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
